// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:3a81a4d2-ef94-46e1-a7a7-c66d8eed22d2",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_5LJxBLcyP",
    "aws_user_pools_web_client_id": "1h7gjgt833pdn2va3gft310lhg",
    "oauth": {
        "domain": "amplify-example.auth.ap-southeast-2.amazoncognito.com",
        "scope": ["openid","email","aws.cognito.signin.user.admin","profile","phone"],
        "redirectSignIn": "https://www.startitgroup.net",
        "redirectSignOut": "https://www.startitgroup.net"
    },
    "aws_user_files_s3_bucket": "aws-amplify-graphqlb516cc19fbe942bc80ac888df3dd67b0-uat",
    "aws_user_files_s3_bucket_region": "ap-southeast-2",
    "aws_appsync_graphqlEndpoint": "https://2mbmmdbhonahtg6nimfuu37gem.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
